// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN4lJAAkFjrMA0uoMl0fau7b5Sx9xvygw',
    appId: '1:96646132979:web:f255e8be7fb1d23d55b386',
    messagingSenderId: '96646132979',
    projectId: 'college-saathi-capstone-9731e',
    authDomain: 'college-saathi-capstone-9731e.firebaseapp.com',
    storageBucket: 'college-saathi-capstone-9731e.appspot.com',
    measurementId: 'G-E4KVV6SEJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1WGJUgjhlKgvDcwp0XH6cgwVd7TNvs5U',
    appId: '1:96646132979:android:af93884a2615d89855b386',
    messagingSenderId: '96646132979',
    projectId: 'college-saathi-capstone-9731e',
    storageBucket: 'college-saathi-capstone-9731e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv3LYN8uZHe5P7_0e1tmi_FmQyMkHD9BU',
    appId: '1:96646132979:ios:8bd97255d784999855b386',
    messagingSenderId: '96646132979',
    projectId: 'college-saathi-capstone-9731e',
    storageBucket: 'college-saathi-capstone-9731e.appspot.com',
    androidClientId: '96646132979-73c5vrsfaen1rdinojor9k8qlfodpimb.apps.googleusercontent.com',
    iosClientId: '96646132979-pfm4ofmiqgcq8k5p4c12m2n2869gcqel.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeSaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv3LYN8uZHe5P7_0e1tmi_FmQyMkHD9BU',
    appId: '1:96646132979:ios:78a0ae4cb85c721855b386',
    messagingSenderId: '96646132979',
    projectId: 'college-saathi-capstone-9731e',
    storageBucket: 'college-saathi-capstone-9731e.appspot.com',
    androidClientId: '96646132979-73c5vrsfaen1rdinojor9k8qlfodpimb.apps.googleusercontent.com',
    iosClientId: '96646132979-j6cros30oju95jcv2bc14vlm0bqot86t.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeSaathi.RunnerTests',
  );
}
